# Introduction to TensorFlow

Before you can build advanced models in TensorFlow 2, you will first need to understand the basics. In this chapter, you’ll learn how to define constants and variables, perform tensor addition and multiplication, and compute derivatives. Knowledge of linear algebra will be helpful, but not necessary. 

# (1) Constants and Variables

## What is TensorFlow?
- Open-source library for graph-based numerical computation
    - Developed by Google Brain Team
- Low and high level APIs
    - Addition, Multiplication, Differentiation
    - Machine Learning models
- Important changes in TensorFlow 2.0
    - Eagger execution by default
    - Model building with Keras and Estimators

## What is Tensor?
- Generalization of vectors and matrices
- Collection of numbers
- Specific shape

## Defining tensors in TensorFlow

In [2]:
import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1, ))

# 1D Tensor
d1 = tf.ones((2, ))

# 2D Tensor
d2 = tf.ones((2, 2))

# 3D Tensor
d3 = tf.ones((2, 2, 2))

print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Defining constants in TensorFlow

A constants is the simplest category of tensor
- Not trainable
- Can have any dimension

In [3]:
from tensorflow import constant

# Define a 2x3 constant.
a = constant(3, shape=[2, 3])

# Define a 2x2 constant.
b = constant([1, 2, 3, 4], shape=[2,2])

## Using convenience functions to define constants

| Operation | Example |
| :- | :- |
| tf.constant() | constant($[1, 2 ,3]$) |
| tf.zeros() | zeros($[2, 2]$) |
| tf.zeros_like | zeros_like(input_tensor) |
| tf.ones() | ones($[2, 2]$) |
| tf.ones_like | ones_like(input_tensor) |
| tf.fills | fills($[3, 3], 7$) |


## Defining and initializing varlables

In [6]:
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

# Define a constant
b = tf.constant(2, tf.float32)

# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0 * b

print(c0, c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32) tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


## Exercise I : Defining data as constants

Throughout this course, we will use tensorflow version 2.4 and will exclusively import the submodules needed to complete each exercise. This will usually be done for you, but you will do it in this exercise by importing constant from tensorflow.

After you have imported constant, you will use it to transform a numpy array, credit_numpy, into a tensorflow constant, credit_constant. This array contains feature columns from a dataset on credit card holders and is previewed in the image below. We will return to this dataset in later chapters.

Note that tensorflow 2 allows you to use data as either a numpy array or a tensorflow constant object. Using a constant will ensure that any operations performed with that object are done in tensorflow. 

<img src="image/default_features.jpg">

Instructions

- Import the constant submodule from the tensorflow module.
- Convert the credit_numpy array into a constant object in tensorflow. Do not set the data type.


In [7]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)

NameError: name 'credit_numpy' is not defined

## Exercise II :    Defining variables

Unlike a constant, a variable's value can be modified. This will be useful when we want to train a model by updating its parameters.

Let's try defining and printing a variable. We'll then convert the variable to a numpy array, print again, and check for differences. Note that Variable(), which is used to create a variable tensor, has been imported from tensorflow and is available to use in the exercise.

Instructions

- Define a variable, A1, as the 1-dimensional tensor: $[1, 2, 3, 4]$.
- Apply .numpy() to A1 and assign it to B1.


In [ ]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)

# (2) Basic Operations

## What is a TensorFlow operation?

<img src="image/Screenshot 2021-01-09 014931.png">

## Applying the addition operator

In [10]:
# Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

# Define 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

# Perform tensor addition with add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

print(C0, C1, C2)

tf.Tensor([3], shape=(1,), dtype=int32) tf.Tensor([4 6], shape=(2,), dtype=int32) tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


## Performing tensor addition

- The add() operation performs element-wise addition with two tensors
- Element-wise addition requires both tensors to have the same shape:
    - Scalar addition: $1 + 2 = 3$

    - Vector addition: $[1, 2] + [3, 4] = [4, 6]$
    
    - Matrix addition: $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
- The add() operation is overloaded

## How to perform multiplication in TensorFlow

- Element-wise multiplication performed using multiply() operation
    - The tensors multiplied must have the same shape
    - E.g. $[1, 2, 3]$ and $[3, 4, 5]$ or $[1, 2]$ and $[3, 4]$
- Matrix multiplication performed with matmul() operator
    - The matmul(A, B) operation multiplies A by B
    - Number of columns of A must equal the number of rows of B

## Apply the multiplication operators

In [14]:
# Import operators from tensorflow
from tensorflow import ones, matmul, multiply

# Define tensors
A0 = ones(1)
A31 = ones([3, 1])
A34 = ones([3, 4])
A43 = ones([4, 3])

print(A0, A31, A34, A43)

tf.Tensor([1.], shape=(1,), dtype=float32) tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32) tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


## What type of operations are did?

- multiply(A0, A0), multiply(A31, A31) and multiply(A34, A34)
- matmul(A43, A34) but not matmul(A43, A43)

## Summing over tensor dimensions

- The reduce_sum() operator sums over the dimensions of a tensor
    - reduce_sum(A) sums over all dimension of A
    - reduce_sum(A, i) sums over dimension i

In [15]:
# Import operations from tensorflow
from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
A = ones([2, 3, 4])

# Sum over all dimension
B = reduce_sum(A)

# Sum over dimension 0, 1, 2
B0 = reduce_sum(A, 0)
B1 = reduce_sum(A, 1)
B2 = reduce_sum(A, 2)

print(A, B, B0, B1, B2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32) tf.Tensor(24.0, shape=(), dtype=float32) tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32) tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


# Exercise III : Performing element-wise multiplication

Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors. An example of an element-wise multiplication, denoted by the (dot) symbol, is shown below:

$\begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}.\begin{bmatrix} 3 & 1 \\ 2 & 5 \end{bmatrix} = \begin{bmatrix} 3 & 2 \\ 4 & 5 \end{bmatrix}$  

In this exercise, you will perform element-wise multiplication, paying careful attention to the shape of the tensors you multiply. Note that multiply(), constant(), and ones_like() have been imported for you.

Instructions

- Define the tensors A1 and A23 as constants.
- Set B1 to be a tensor of ones with the same shape as A1.
- Set B23 to be a tensor of ones with the same shape as A23.
- Set C1 and C23 equal to the element-wise products of A1 and B1, and A23 and B23, respectively.

In [ ]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))

# Exercise IV : Making predictions with matrix multiplication

In later chapters, you will learn to train linear regression models. This process will yield a vector of parameters that can be multiplied by the input data to generate predictions. In this exercise, you will use input data, features, and a target vector, bill, which are taken from a credit card dataset we will use later in the course.

$features = \begin{bmatrix} 2 & 24 \\ 2 & 26 \\ 2 & 57 \\ 1 &37\end{bmatrix}, bill = \begin{bmatrix} 3913 \\ 2682 \\ 8617 \\ 64400 \end{bmatrix}, params=\begin{bmatrix} 1000 \\ 150 \end{bmatrix}$

The matrix of input data, features, contains two columns: education level and age. The target vector, bill, is the size of the credit card borrower's bill.

Since we have not trained the model, you will enter a guess for the values of the parameter vector, params. You will then use matmul() to perform matrix multiplication of features by params to generate predictions, billpred, which you will compare with bill. Note that we have imported matmul() and constant().

Instructions
- Define features, params, and bill as constants.
- Compute the predicted value vector, billpred, by multiplying the input data, features, by the parameters, params. Use matrix multiplication, rather than the element-wise product.
- Define error as the targets, bill, minus the predicted values, billpred.

In [ ]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

# Exercise V : Summing over tensor dimensions

You've been given a matrix, wealth. This contains the value of bond and stock wealth for five individuals in thousands of dollars.

$wealth = \begin{bmatrix} 11 & 50 \\ 7 & 2 \\ 4 & 60 \\ 3 & 0 \\ 25 & 10 \end{bmatrix}$

The first column corresponds to bonds and the second corresponds to stocks. Each row gives the bond and stock wealth for a single individual. Use wealth, reduce_sum(), and .numpy() to determine which statements are correct about wealth.

Possible Answers

- The individual in the first row has the highest total wealth (i.e. stocks + bonds).

- Combined, the 5 individuals hold $50,000 in stocks.

- [True] Combined, the 5 individuals hold $50,000 in bonds.

- The individual in the second row has the lowest total wealth (i.e. stocks + bonds).

# (3) Advance operations

## Overview of advanced operations
- We have covered basic operations in Tensorflow
    - add(), multiply(), matmul() and reduce_sum()
- In this lesson, we explore advanced operations
    - gradient(), reshape() and random()

| Operation | Use |
| :- | :- |
| gradient() | Computes the slope of a function at a point |
| reshape() | Reshapes a tensor (e.g. 10x10 to 100x1)
| random() | Populates tensor with entries drawn from a probability distribution |

## Finding the optimum
- In many problems, we will want to find the optimum of a function.
    - Minimum: Lowest value of a loss function.
    - Maximum: Highest value of objective function.
- We can do this using the gradient() Operation.
    - Optimum: Find a point where grdient = 0
    - Minimum: Change in gradient > 0

## Calculating the gradient

<img src="image/Screenshot 2021-01-09 195246.png" width="50%" height="50%">

<img src="image/Screenshot 2021-01-09 195309.png" width="50%" height="50%">

## Gradients in Tensorflow

In [4]:
# Import tensorflow under the alias tf
import tensorflow as tf

# Define X
x = tf.Variable(-1.0)

# Define y within instance of GradientTape
with tf.GradientTape() as tape:
    tape.watch(x)
    y.multiply(x, x)

# Evaluate the gradient of y at x = -1
g = tape.gradient(y, x)
print(g.numpy())

ModuleNotFoundError: No module named 'tensorflow'