# Introduction to TensorFlow

Before you can build advanced models in TensorFlow 2, you will first need to understand the basics. In this chapter, you’ll learn how to define constants and variables, perform tensor addition and multiplication, and compute derivatives. Knowledge of linear algebra will be helpful, but not necessary. 

# (1) Constants and Variables

## What is TensorFlow?
- Open-source library for graph-based numerical computation
    - Developed by Google Brain Team
- Low and high level APIs
    - Addition, Multiplication, Differentiation
    - Machine Learning models
- Important changes in TensorFlow 2.0
    - Eagger execution by default
    - Model building with Keras and Estimators

## What is Tensor?
- Generalization of vectors and matrices
- Collection of numbers
- Specific shape

## Defining tensors in TensorFlow

In [2]:
import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1, ))

# 1D Tensor
d1 = tf.ones((2, ))

# 2D Tensor
d2 = tf.ones((2, 2))

# 3D Tensor
d3 = tf.ones((2, 2, 2))

print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Defining constants in TensorFlow

A constants is the simplest category of tensor
- Not trainable
- Can have any dimension

In [3]:
from tensorflow import constant

# Define a 2x3 constant.
a = constant(3, shape=[2, 3])

# Define a 2x2 constant.
b = constant([1, 2, 3, 4], shape=[2,2])

## Using convenience functions to define constants

| Operation | Example |
| :- | :- |
| tf.constant() | constant($[1, 2 ,3]$) |
| tf.zeros() | zeros($[2, 2]$) |
| tf.zeros_like | zeros_like(input_tensor) |
| tf.ones() | ones($[2, 2]$) |
| tf.ones_like | ones_like(input_tensor) |
| tf.fills | fills($[3, 3], 7$) |


## Defining and initializing varlables

In [6]:
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

# Define a constant
b = tf.constant(2, tf.float32)

# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0 * b

print(c0, c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32) tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


## Exercise I : Defining data as constants

Throughout this course, we will use tensorflow version 2.4 and will exclusively import the submodules needed to complete each exercise. This will usually be done for you, but you will do it in this exercise by importing constant from tensorflow.

After you have imported constant, you will use it to transform a numpy array, credit_numpy, into a tensorflow constant, credit_constant. This array contains feature columns from a dataset on credit card holders and is previewed in the image below. We will return to this dataset in later chapters.

Note that tensorflow 2 allows you to use data as either a numpy array or a tensorflow constant object. Using a constant will ensure that any operations performed with that object are done in tensorflow. 

<img src="image/default_features.jpg">

Instruction

- Import the constant submodule from the tensorflow module.
- Convert the credit_numpy array into a constant object in tensorflow. Do not set the data type.


In [7]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)

NameError: name 'credit_numpy' is not defined

## Exercise II :    Defining variables

Unlike a constant, a variable's value can be modified. This will be useful when we want to train a model by updating its parameters.

Let's try defining and printing a variable. We'll then convert the variable to a numpy array, print again, and check for differences. Note that Variable(), which is used to create a variable tensor, has been imported from tensorflow and is available to use in the exercise.

Instruction

- Define a variable, A1, as the 1-dimensional tensor: $[1, 2, 3, 4]$.
- Apply .numpy() to A1 and assign it to B1.


In [ ]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)

# (2) Basic Operations

## What is a TensorFlow operation?

<img src="image/Screenshot 2021-01-09 014931.png">

## Applying the addition operator

In [10]:
# Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

# Define 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

# Perform tensor addition with add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

print(C0, C1, C2)

tf.Tensor([3], shape=(1,), dtype=int32) tf.Tensor([4 6], shape=(2,), dtype=int32) tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


## Performing tensor addition

- The add() operation performs element-wise addition with two tensors
- Element-wise addition requires both tensors to have the same shape:
    - Scalar addition: $1 + 2 = 3$

    - Vector addition: $[1, 2] + [3, 4] = [4, 6]$
    
    - Matrix addition: $\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
- The add() operation is overloaded

## How to perform multiplication in TensorFlow

- Element-wise multiplication performed using multiply() operation
    - The tensors multiplied must have the same shape
    - E.g. $[1, 2, 3]$ and $[3, 4, 5]$ or $[1, 2]$ and $[3, 4]$
- Matrix multiplication performed with matmul() operator
    - The matmul(A, B) operation multiplies A by B
    - Number of columns of A must equal the number of rows of B